version: "3.9"

services:
  sphinx_html:
    container_name: sphinx_html
    build:
      context: ./docs
      dockerfile: Dockerfile_html
    image: sphinxdoc/sphinx-html
    ports:
      - "8080:80"
    volumes:
      - "${PWD}/docs/source:/etc/Sphinx/source"
      - "${PWD}/docs/build:/etc/Sphinx/build"
      - "${PWD}/pythonScripts:/etc/pythonScripts"  
    restart: unless-stopped
  
  sphinx_pdf:
    container_name: sphinx_pdf
    build:
      context: ./docs
      dockerfile: Dockerfile_latex
    image: sphinxdoc/sphinx-latexpdf
    volumes:
      - "${PWD}/docs/source:/etc/Sphinx/source"
      - "${PWD}/docs/build:/etc/Sphinx/build"
      - "${PWD}/pythonScripts:/etc/pythonScripts"  
    restart: unless-stopped



