version: "3.9"

services:
  sphinx:
    container_name: sphinx_html
    build:
      context: ./docs
      dockerfile: Dockerfile
    image: sphinxdoc/sphinx
    ports:
      - 8080:80
    volumes:
      - "./docs/source:/etc/Sphinx/source"
      - "./docs/build:/etc/Sphinx/build"
      - "./pythonScripts:/etc/pythonScripts"
