FROM alpine:3.15.0

COPY requirements.txt /etc

RUN apk add --no-cache \
        python3 make git py3-pip \
        texlive \
        texlive-xetex \
        texmf-dist \
        texmf-dist-formatsextra \
        texmf-dist-latexextra \
        texmf-dist-pictures \
        texmf-dist-science \
        && mkdir -p \
        /etc/Sphinx/build \
        /etc/Sphinx/build/pdf \
        /etc/Sphinx/source \
        /etc/pythonScripts \
        && pip3 install -r /etc/requirements.txt

COPY sphinxConfig.yml /etc

COPY /source /etc/Sphinx/source

CMD ["sphinx-autobuild", "-b", "latex", "/etc/Sphinx/source", "/etc/Sphinx/build/pdf"]
